remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Samuel Zhao's Project Portfolio
description: ðŸ“§samandzhao@gmail.com  |  ðŸ“ž(737)-296-0548
show_downloads: true
google_analytics: G-93YXP21YQB
